### ISSUE TITLE
Test Framework Work

### ISSUE THREAD

**Issue by tgross35** [pluots/zspell#10]
Need to figure out what is needed here, and how the API should work.

Also need a nicer testing framework, maybe something like this:

```
==== afx ====
...
==== dic ====
...
==== wordlist ====
abc
def
==== wordlist_nosuggest ====
ghi
==== suggestions ====
aaple > apple | apfel | app
```

**Comment by tgross35** [comment]
Test framework has been implemented as of 2a2bec992ff9a3695130643f9b86d7ac28910533

**Comment by tgross35** [comment]
It would probably be good to have suggestions return an enum. I.e.:

```rust
enum Suggestions {
    Correct
    Incorrect(Vec<String>)
}
```

**Comment by tgross35** [comment]
Changing this issue to test framework only so it can be closed. New suggestion work in #16

**Comment by sumansuhag** [comment]
Hey tgross35, 

it sounds like you're working on an interesting text processing or search system! Making sure the API design is solid and the testing is straightforward is definitely important.

When it comes to designing your API, think about these key points:

1. **Clear Data Contracts**: Define what your API takes in (like text, language code, max suggestions) and what it gives back (like an array of suggestions with original words, corrections, scores, and languages). Common formats are JSON for RESTful apps or GraphQL for flexible querying.

2. **Statelessness**: Ensure your endpoints don’t depend on previous requests. This makes them easier to scale and test.

3. **Error Handling**: Have clear error codes for situations like invalid input, no suggestions found, or internal errors.

4. **Configuration**: Decide how you’ll load and update your afx, dic, and wordlist files. Will your API allow management of these through endpoints, or will they be set up at deployment?

For a better testing framework, your idea with the ==== sections ==== is a smart move for readability. Here are a couple of approaches to consider:

- **Behavior-Driven Development (BDD)**: Using tools like Behave (Python) or Cucumber (for various languages) with Gherkin syntax can help you write simple, human-readable tests. For example:
  
  ```gherkin
  Scenario: Generate suggestions for a common misspelling
    Given the wordlist contains apple, apfel, app
    When the API receives the word aaple
    Then the suggestions should include apple, apfel, app
  ```

- **Data-Driven Testing**: Keep your wordlist, wordlist_nosuggest, and suggestions in external files like CSV, JSON, or YAML. Your test framework can go through them easily, making it simple to scale and update tests. Using pytest fixtures with external data sources can help with this in Python.

A framework like this not only checks that everything works but also acts as helpful documentation for how your API should behave. What’s the toughest design decision you’re facing right now? Maybe it has to do with managing the suggestion logic or handling data sources?
