### ISSUE TITLE
Failed to parse french hunspell dictionary

### ISSUE THREAD

**Issue by gwen-lg** [pluots/zspell#108]
In french dictionary, flags can have multiple characters.
Ex:
`
NEEDAFFIX ()
FORBIDDENWORD {}
CIRCUMFIX **
KEEPCASE ||
NOSUGGEST --
`

and it's not correctly handeled

**Comment by tgross35** [comment]
@gwen-lg I think I fixed the flag issue in https://github.com/pluots/zspell/pull/111. Any chance you could test with the French dictionary and see if you are getting reasonable results?

I'll release later today if it looks okay.

**Comment by gwen-lg** [comment]
@tgross35 : yes, the build of dictionary work, and give reasonable results.
Thank you

**Comment by gwen-lg** [comment]
Probably not related, but zspell seems not to recognize plurals and verb conjugations.

**Comment by tgross35** [comment]
Thanks for confirming 👍 I'll get a release ready.

Do you have a specific example of plurals or conjugations? I suspect this probably needs lazy word checking (WIP...)

**Comment by gwen-lg** [comment]
In the sentence : `Même mourant, vous répondez présent.`
the word `répondez` is detected as error, while it's a conjugation of the verb `répondre`
`projections` is not detected as plural of `projection`.

**Comment by tgross35** [comment]
Thanks for the reproduction, I wrote that up in https://github.com/pluots/zspell/issues/116. It will unfortunately need a new feature.

The original issue should be fixed with the new release 0.5.5. I understand that unfortunately doesn't get far when there are no plurals :)
