### ISSUE TITLE
Failed to load `de-*` dictionaries.

### ISSUE THREAD

**Issue by antonWetzel** [pluots/zspell#93]
Tested with <https://github.com/antonWetzel/typst-hunspell/tree/zspell>.

Loading the dictionaries `de`, `de-AT` and `de-CH` from <https://github.com/wooorm/dictionaries> fails with `Build(DuplicateFlag { flag: "f", t1: AfxCircumfix, t2: None })`.

The wrapper `hunspell-rs` loads the dictionaries without visible error, so I don't know if the dictionaries are malformed and the errors are ignored or the problem is produced by zspell.

**Comment by tgross35** [comment]
Thanks for the report! I had tested with the German dictionary at some point and it was working, so I will take a look at what changed.

**Comment by tgross35** [comment]
Fixed in #96, we still don't handle circumfix correctly but at least we can load the dictionary
